### ISSUE TITLE
Zombies not spawning in local server

### ISSUE THREAD

**Issue by Joshikumako** [Reperio-Studios/BrainBread-2-Issues#3]
the game doesnt load in zombies if you create a local server.

**Comment by jonnyboy0719** [comment]
Zombies do not work on the old maps:
- bbc_factory
- bbc_farm
- bbc_urban_escape

Since they are using the old zombie spawn trigger, and not the new one. And to make zombies spawn on Survival mode, you need to write **bb2_roundstart_requiredplayers 1** to make sure they spawn (later on, Survival mode minimum required players will be 2).

You can also add a bot any time by writing **bot** on the console (make sure you have **sv_cheats** set to 1).
